version: "3"
services:
  app:
    build: .
    command: node build/main.js
    volumes:
      - bot.db:/bot.db
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - PRIMARY_GUILD_ID=${PRIMARY_GUILD_ID}
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
