version: "3"
services:
  app:
    build: .
    command: sh -c "pnpx prisma migrate deploy && node build/main.js"
    volumes:
      - ./data:/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - PRIMARY_GUILD_ID=${PRIMARY_GUILD_ID}
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
      - UPDATES_CHANNEL_ID=${UPDATES_CHANNEL_ID}
