version: "3"
services:
  app:
    build: .
    volumes:
      - ./data:/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - PRIMARY_GUILD_ID=${PRIMARY_GUILD_ID}
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
