version: "3"
services:
  app:
    build: .
    restart: always
    command: sh -c "pnpx prisma migrate deploy && node build/main.js"
    volumes:
      - ./data:/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL:postgres://postgres:password@postgres:5432/raboneko}
      - PRIMARY_GUILD_ID=${PRIMARY_GUILD_ID}
      - ANNOUNCEMENTS_CHANNEL_ID=${ANNOUNCEMENTS_CHANNEL_ID}
      - UPDATES_CHANNEL_ID=${UPDATES_CHANNEL_ID}
      - GENERAL_CHANNEL_ID=${GENERAL_CHANNEL_ID}
      - REDIS_HOST=${REDIS_HOST:redis}
      - REDIS_PORT=${REDIS_PORT:6379}
  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=raboneko
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  postgres:
